-- ====================================================================
-- ORACLE SQL*PLUS GLOBAL CLEAN FORMATTER (EVERY TABLE)
-- Save this file as "clean.sql"
-- Usage inside SQL*Plus:  SQL> @clean
-- ====================================================================

-- 1. Setup global line and screen limits
SET LINESIZE 250;
SET PAGESIZE 50;
SET WRAP ON;
SET HEADING ON;
SET TAB OFF;

-- 2. Compress common generic column names used across all database tables
COLUMN ID FORMAT 99999 HEADING "ID";
COLUMN *ID FORMAT 99999;
COLUMN STATUS FORMAT A10;
COLUMN NAME FORMAT A20;
COLUMN TYPE FORMAT A12;
COLUMN CODE FORMAT A8;

-- 3. Standardize date formats so they don't stretch
COLUMN CREATED_AT FORMAT A15 HEADING "CREATED";
COLUMN UPDATED_AT FORMAT A15 HEADING "UPDATED";
COLUMN START_DATE FORMAT A11 HEADING "START";
COLUMN END_DATE FORMAT A11 HEADING "END";

-- 4. Global table configurations for your specific current tables
-- Table: ADMIN
COLUMN ADMIN_ID FORMAT 9999 HEADING "ADMIN_ID";
COLUMN FULL_NAME FORMAT A20 HEADING "FULL NAME";
COLUMN EMAIL FORMAT A25 HEADING "EMAIL";
COLUMN ROLE FORMAT A15 HEADING "ROLE";

-- Table: VENUE
COLUMN VENUE_ID FORMAT 9999 HEADING "VENUE_ID";
COLUMN VENUE_NAME FORMAT A20 HEADING "VENUE NAME";
COLUMN BUILDING FORMAT A15 HEADING "BUILDING";
COLUMN ROOM_NUMBER FORMAT A12 HEADING "ROOM";
COLUMN CAPACITY FORMAT 99999 HEADING "CAPACITY";
COLUMN H FORMAT A3 HEADING "H";
COLUMN I FORMAT A3 HEADING "I";

-- Table: CLUB
COLUMN CLUB_ID FORMAT 9999 HEADING "CLUB_ID";
COLUMN CLUB_NAME FORMAT A15 HEADING "CLUB NAME";
COLUMN CATEGORY FORMAT A10 HEADING "CATEGORY";
COLUMN DESCRIPTION FORMAT A35 HEADING "DESCRIPTION";
COLUMN ESTABLISH FORMAT A11 HEADING "ESTABLISHED";
COLUMN CREATED_BY_ADMIN_ID FORMAT 9999 HEADING "ADMIN ID";

PROMPT Global clean formatting configuration loaded successfully!
